sudo: required

# language: python
language: node_js

services:
  - docker

# python:
#  - "3.6"

node_js:
  - 12

branches:
  only:
    - master

install:
  - pyenv global 3.7.1
  - make install

script:
  - make start

notifications:
  email: false
