service: localstack-demo

plugins:
  - serverless-deployment-bucket
  - serverless-localstack

provider:
  name: aws
  stage: local
  region: us-east-1
  stackName: demo1
  timeout: 15
  deploymentBucket:
    name: localstack-test-bucket

package:
  excludeDevDependencies: true
  exclude:
    - ./**
    - "!demo/**"
    - "!node_modules/uuid/**"

custom:
  region: us-east-1
  accountID: '000000000000'
  localstack:
    stages: [local]
    debug: true
    # Note: enable this configuration to automatically start up a LocalStack container in the background
#    autostart: true
    # lambda:
    #   mountCode: true

functions:
  http_handleRequest:
    handler: demo/lambdas/app.handleRequest
    runtime: nodejs14.x
    events:
      - http:
          path: /requests
          method: post
          cors: true
      - http:
          path: /requests
          method: get
          cors: true
  sqs_handleItem:
    handler: demo/lambdas/worker.triggerProcessing
    runtime: ruby2.7
    events:
      - sqs:
          arn:
            Fn::GetAtt: [requestQueue, Arn]
  backend_processRequest:
    handler: demo/lambdas/processing.handleRequest
    runtime: python3.7
  backend_archiveResult:
    handler: demo/lambdas/processing.archiveResult
    runtime: python3.7

resources:
  Resources:
    appDatabase:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: appRequests
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: requestID
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: requestID
            KeyType: RANGE
    archiveBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: archive-bucket
    requestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: requestQueue
    processingStateMachine:
      Type: AWS::StepFunctions::StateMachine
      Properties:
        StateMachineName: processingStateMachine
        RoleArn: arn:aws:iam::000000000000:role/test
        DefinitionString: |
          {
            "StartAt": "ProcessRequest",
            "States": {
              "ProcessRequest": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:${self:provider.region}:${self:custom.accountID}:function:${self:service}-${self:provider.stage}-backend_processRequest",
                "Next": "ArchiveResult"
              },
              "ArchiveResult": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:${self:provider.region}:${self:custom.accountID}:function:${self:service}-${self:provider.stage}-backend_archiveResult",
                "End": true
              }
            }
          }
