version: '2.1'

orbs:
  localstack: localstack/platform@1.0.1

jobs:
  localstack-test:
    executor: localstack/default
    environment:
      CI_PROJECT: ci123
      DATA_DIR: /tmp/ls-data
      DNS_ADDRESS: "0"
    steps:
      - checkout
      - run: docker pull localstack/localstack
      - localstack/startup
      - run:
          name: Deploy app and run test request
          command: |
            awslocal s3 mb s3://test
            awslocal s3 ls
            make install
            make start
            make send-request
            code=$?
            docker logs localstack_main
            exit $code

workflows:
  localstack-test:
    jobs:
      - localstack-test
